services:
  prometheus:
    image: prom/prometheus:v2.52.0-rc.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/debian/stacks/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/debian/stacks/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - /home/debian/stacks/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:

