version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.52.0-rc.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /root/repositorios/prometheus-grafana-alertmanager/prometheus.yml:/etc/prometheus/prometheus.yml
      - /root/repositorios/prometheus-grafana-alertmanager/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - prometheus_data:/prometheus
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - /root/repositorios/prometheus-grafana-alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring

  discord-alerts:
    image: benjojo/discord-alertmanager:latest
    container_name: discord-alerts
    environment:
      - DISCORD_WEBHOOK="https://discord.com/api/webhooks/1333528482583679110/_owHuy07asC6PgQ4js_IQb1_ZQElSfdCgTKYmuLBU_e3LHg13iyE0J_oKpwa9FNc0zQx"
    ports:
      - "9094:9094" # Opcional, puedes cambiarlo o eliminarlo si no necesitas exponerlo
    depends_on:
      - alertmanager
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:

